let x = Math.floor(Math.random() * 10);
let number = Math.pow(10, x);
console.log(number);
if(number==1) console.log("Unit");
else if(number==10) console.log("Ten");
else if(number==100) console.log("Hundred");
else if(number==1000) console.log("Thousand");
else if(number==10000) console.log("Ten Thousand");
else if(number==100000) console.log("Hundreds of Thousands");
else if(number==1000000) console.log("Million");
else if(number==10000000) console.log("Ten Million");
else if(number==100000000) console.log("Hundreds of Millions");
else console.log("Billion");